server:
  port: 80
  context-path: /cartoon
  max-http-header-size: 10000000

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql