server:
  port: 80
  context-path: /
  max-http-header-size: 10000000

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# 定位模板的目录
# 给返回的页面添加后缀名
spring:
    mvc:
        view:
            prefix: classpath:/templates/
            suffix: .html